name: Update GitHub Profile README

on:
  schedule:
    - cron: '0 0 * * *' # Her gün 00:00'da çalışacak
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate contribution graph gif
        uses: mishmanners/github-contribution-grid-snake@main
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          username: Alimanay
          update_readme: true
